apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rd
  spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: myapp
      labels:
        app: nginx
    spec:
      containers:
        - name: simple-pod
          image: nginx
          ports:
            - containerPort: 80
